# Dependencies
highlighter:      rouge

# gems
gems: [jekyll-paginate, jekyll-gist, jekyll-seo-tag]
paginate:         5

# Permalinks
permalink:        pretty

# Setup
title:            Patrick's Blog
description:      'Howdy, welcome to my blog! Random stuff on open source, web technologies, Linux and much more can be found here.'

# Social URLs
github-url: https://github.com/apophis90
linkedin-url: https://de.linkedin.com/in/pkleindienst
twitter-url: https://twitter.com/Apophis1990

# Additional details for Jekyll SEO plugin
social:
  name: Patrick Kleindienst
  links:
    - https://twitter.com/Apophis1990
    - https://de.linkedin.com/in/pkleindienst
    - https://github.com/apophis90
